version: '3'
services:
  nginx:
    ports:
    - "3000:80"
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=lokesh
      - MONGO_PASSWORD=mypassword
      
    # env_file:
      # - ./.env
    command: npm run dev

  mongo:
    
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lokesh
      MONGO_INITDB_ROOT_PASSWORD: mypassword


volumes:
  mongo-db: