version: '3'
services:
  nginx:
    image: nginx
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    image: lokeshchhatani/node-app
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=3000
    depends_on:
      - mongo 
    # env_file:
      # - ./.env

  mongo:
    
    image : mongo:4.4.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lokesh
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: